- name: catalogue configuration
  hosts: catalogue
  become: yes
  tasks:
  - name: Enable nodejs 20 version
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: create system user roboshop
    ansible.builtin.user:
     name: "roboshop"
     system: true
     home: "/app"
     shell: "/sbin/nologin"
     comment: "roboshop system user"

  - name: remove app directory
    ansible.builtin.file:
      path: "/app"
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: "/app"
      state: directory

  - name: remove catalogue zip file
    ansible.builtin.file:
      path: "/tmp/catalogue.zip"
      state: absent

  - name: get data from url
    ansible.builtin.get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip"
      dest: "/tmp/catalogue.zip"
  
  - name: unzip catalogue
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: true
  
  - name: install npm package
    ansible.builtin.package:
      name: "npm"
      state: present

  - name: install npm dependencies
    community.general.npm:
      path: /app

  - name: copy catalogue.service file
    ansible.builtin.template:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: daemon-reload 
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  
  - name: install mongodb client
    ansible.builtin.dnf:
      name: "mongodb-mongosh"
      state: present
  
  - name: check if schema exists
    ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output
  
  - name: print output 
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"
  
  - name: load product data
    ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalogue_output.stdout | int < 0

  - name: start and enable catalogue service
    ansible.builtin.service: 
      name: catalogue
      state: restarted
      enabled: yes

  # - name: reload catalogue services
  #   ansible.builtin.systemd:
  #     name: "daemon-reload"
  #     state: restarted
  # - name: catalogue enable and start
  #   ansible.builtin.service:
  #     name: "catalogue"
  #     state: started
  #     enabled: true

