- name: configure payment
  hosts: payment
  become: yes
  tasks:
  - name: install python3 gcc python3-devel
    ansible.builtin.dnf:
      name: "{{ item }}"
    loop:
    - python3
    - gcc
    - python3-devel
  
  - name: create system user roboshop
    ansible.builtin.user:
     name: "roboshop"
     system: true
     home: "/app"
     shell: "/sbin/nologin"
     comment: "roboshop system user"

  - name: remove app directory
    ansible.builtin.file:
      path: "/app"
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: "/app"
      state: directory

  - name: remove payment zip file
    ansible.builtin.file:
      path: "/tmp/payment.zip"
      state: absent

  - name: get data from url
    ansible.builtin.get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip"
      dest: "/tmp/payment.zip"
  
  - name: unzip payment
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: true
  
  - name: install dependencies
    ansible.builtin.pip:
      name: requirements.txt
      executable: pip3.9
    args:
      chdir: "/app"
  
  - name: copy payment service
    ansible.builtin.template:
      src: payment.service
      dest: /etc/systemd/system/payment.service
  
  - name: daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  - name: start and enable payment service
    ansible.builtin.service:
      name: payment
      enabled: yes
      state: started