- name: create ec2 and route 53 records
  hosts: all
  connection: local
  vars:
    instances:
    - mongo
    - catalogue
    env: dev
    instance_type: t3.micro
    sg_id: sg-038655dad535c0654
    image_id: ami-0220d79f3f480ecf5
    domain_name: happielearning.com
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "{{ instance_type}}"
      image_id: "{{ image_id }}"
      security_group: "{{ sg_id }}"
      name: "{{ item }}-{{ env }}"
      tags:
        Project: "roboshop"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    loop: "{{ instances }}"
    register: instances_output
  
  - name: Add new.foo.com as an A record with 3 IPs and wait until the changes have been replicated
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}-{{ env }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ instances_output.results }}"