- name: create ec2 instances
  hosts: all
  connection: local
  vars:
    instances:
      - mongo
      - catalogue
    env: dev
    instance_type: t3.micro
    sg_id: sg-038655dad535c0654
    image_id: ami-0220d79f3f480ecf5
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "{{ instance_type}}"
      image_id: "{{ image_id }}"
      security_group: 
      name: "{{ item }}-{{ env }}"
      tags:
        Project: "roboshop"
        Environment: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: instances_output